import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <div className="navbar bg-neutral text-neutral-content">
        <div className="flex-1">
          <Link href={'#'}>
            <a className="btn normal-case text-xl">کافه میکس</a>
          </Link>
        </div>
        <div className="flex-none gap-2">
          <ul className="menu menu-horizontal p-0">
            <li>
              <a className="btn normal-case font-normal" href="/register">
                عضویت
              </a>
            </li>
            <li>
              <a className="btn normal-case font-normal" href="/login">
                ورود
              </a>
            </li>
          </ul>

          <div className="form-control">
            <input type="text" placeholder="جستجو" className="input input-bordered" />
          </div>
          <div className="dropdown dropdown-end">
            <label className="btn btn-ghost btn-circle avatar">
              <div className="w-10 rounded-full">
                <img src="https://placeimg.com/80/80/people" />
              </div>
            </label>
            <ul className="mt-3 p-2 shadow menu menu-compact dropdown-content bg-neutral text-neutral-content rounded-box w-52">
              <li>
                <a className="justify-between">
                  پروفایل
                  <span className="badge bg-accent-focus text-primary-content">جدید</span>
                </a>
              </li>
              <li>
                <a>تنظیمات</a>
              </li>
              <li>
                <a>خروج</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <a className="btn btn-primary">سلام دنیا</a>
          ترکیبی از nextjs و daisyUI با فونت فارسی
        </main>

        <footer className={styles.footer}>
          <Link href={'https://github.com/cafecodingir/next-cafe'}>مخزن</Link>
        </footer>
      </div>
    </>
  )
}

export default Home
