import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <a className="btn btn-primary">سلام دنیا</a>
        ترکیبی از nextjs و daisyUI با فونت فارسی
      </main>

      <footer className={styles.footer}>
        <Link href={'https://github.com/cafecodingir/next-cafe'}>مخزن</Link>
      </footer>
    </div>
  )
}

export default Home
